version: '3'
services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: digitalocean.com/php
    container_name: BookSystem_app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - booksystem-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: BookSystem_webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - booksystem-network

#  #MySQL Service
#  db:
#    image: mysql:5.7.22
#    container_name: db
#    restart: unless-stopped
#    tty: true
#    ports:
#      - "3306:3306"
#    environment:
#      MYSQL_DATABASE: laravel
#      MYSQL_ROOT_PASSWORD: your_mysql_root_password
#      SERVICE_TAGS: dev
#      SERVICE_NAME: mysql
#      volumes:
#        - dbdata:/var/lib/mysql
#    networks:
#      - app-network

#Docker Networks
networks:
  booksystem-network:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local
